[package]
name = "cosmic-ext-redeye"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "Blue light filter applet for COSMIC"
repository = "https://github.com/big-ol-pants/cosmic-ext-redeye"

[dependencies]
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
rust-embed = "8.8.0"
tempfile = "3.27.0"
wayland-client = "0.31.14"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
# Remove features if not needed.
features = [
    # GPU-accelerated rendering
    "wgpu",
    # COSMIC panel applet runner and popup helpers
    "applet",
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
