## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# Generated using the scripts at # Generated using the scripts at https://forge.fedoraproject.org/cosmic/cosmic-packaging/src/branch/main/scripts
ExcludeArch: %{ix86}
# Generated by rust2rpm 26
%bcond_without check


# While our version corresponds to an upstream tag, we still need to define
# these macros in order to set the VERGEN_GIT_SHA and VERGEN_GIT_COMMIT_DATE
# environment variables in multiple sections of the spec file.
%global commit a55785993e8ef6aad38862cb1a9e1ccaad3c340d
%global commitdatestring 2026-09-09 15:54:44 +0200
%global cosmic_minver 1.8.0

# rustc was OOM-killed linking the cosmic-comp binary (10.1 GB anon-rss on a 15 GB
# box). debuginfo=2 is what inflates it; we do not need debug symbols here.
# codegen-units>1 also lowers peak memory per unit and restores parallelism.
%global rustflags_debuginfo 0
%global rustflags_codegen_units 16
%global debug_package %{nil}

Name:           cosmic-comp
Version: 1.8.0
Release:        1.gamma1%{?dist}
Summary:        Compositor for the COSMIC Desktop Environment

License: (0BSD OR Apache-2.0 OR MIT) AND (Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT) AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSD-3-Clause OR MIT) AND (Apache-2.0 OR BSD-3-Clause) AND (Apache-2.0 OR CC0-1.0 OR MIT) AND (Apache-2.0 OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-or-later OR MIT) AND (Apache-2.0 OR MIT OR Unlicense) AND (Apache-2.0 OR MIT OR Zlib) AND (Apache-2.0 OR MIT) AND (LGPL-3.0-or-later OR MIT) AND (MIT OR Unlicense) AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND GPL-3.0-only AND ISC AND MIT AND MPL-2.0 AND Unicode-3.0 AND Zlib

URL:            https://github.com/pop-os/cosmic-comp

Source0:        https://github.com/pop-os/cosmic-comp/archive/epoch-%{version_no_tilde}/cosmic-comp-%{version_no_tilde}.tar.gz
# To create the below sources:
# * git clone https://github.com/pop-os/cosmic-comp at the specified commit
# * cargo vendor > vendor-config-%%{version_no_tilde}.toml
# * tar -pczf vendor-%%{version_no_tilde}.tar.gz vendor
Source1:        vendor-%{version_no_tilde}.tar.gz
# * mv vendor-config-%%{version_no_tilde}.toml ..
Source2:        vendor-config-%{version_no_tilde}.toml

# wlr-gamma-control-unstable-v1, rebased from pop-os/cosmic-comp#2417 onto epoch-1.8.0
Patch0:         gamma-on-1.8.0.patch

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  libglvnd-devel
BuildRequires:  libseat-devel
BuildRequires:  libinput-devel
BuildRequires:  mesa-libgbm-devel
BuildRequires:  pixman-devel
BuildRequires:  libdisplay-info-devel
BuildRequires:  make

Requires:       libseat%{?_isa}
Requires:       libwayland-server%{?_isa}
Requires:       xorg-x11-server-Xwayland
Requires:       cosmic-icon-theme >= %{cosmic_minver}

Recommends:     cosmic-session

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-comp-epoch-%{version_no_tilde} -p1 -a1
%cargo_prep -N
# Check if .cargo/config.toml exists
if [ -f .cargo/config.toml ]; then
  # If it exists, append the contents of %%{SOURCE2} to .cargo/config.toml
  cat %{SOURCE2} >> .cargo/config.toml
  echo "Appended %{SOURCE2} to .cargo/config.toml"
else
  # If it does not exist, append the contents of %%{SOURCE2} to .cargo/config
  cat %{SOURCE2} >> .cargo/config
  echo "Appended %{SOURCE2} to .cargo/config"
fi

%build
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
export GIT_HASH="%{commit}"
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1+git\2/' -i cargo-vendor.txt
sed 's/^\([^+]*\)+.*+\([^+]*\)$/\1+\2/' -i cargo-vendor.txt

%install
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
export GIT_HASH="%{commit}"
make install DESTDIR=%{buildroot} prefix=%{_prefix}

%if %{with check}
%check
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
export GIT_HASH="%{commit}"
# Don't cargo test until https://github.com/pop-os/cosmic-comp/issues/1791 is resolved.
# %%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%{_bindir}/cosmic-comp
%{_datadir}/cosmic/com.system76.CosmicSettings.Shortcuts/v1/defaults
%{_datadir}/cosmic/com.system76.CosmicSettings.WindowRules/v1/tiling_exception_defaults

%changelog
* Tue Sep 15 2026 local <local> - 1.8.0-1.gamma1
- Add wlr-gamma-control-unstable-v1 (rebased from upstream PR #2417)

## START: Generated by rpmautospec
* Wed Sep 09 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.8.0-1
- Update to 1.8.0

* Thu Aug 20 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.6.0-3
- Update to 1.6.0

* Thu Aug 20 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.6.0-2
- Update to 1.6.0

* Thu Aug 20 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.6.0-1
- Update to 1.6.0

* Thu Jul 30 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.5.0-1
- Update to 1.5.0

* Thu Jul 23 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.4.0-1
- Update to 1.4.0

* Wed Jul 15 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.3.0-1
- Update to 1.3.0

* Wed Jun 24 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.1.0-1
- Update to 1.1.0

* Wed Jun 10 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.16-1
- Update to 1.0.16

* Thu Jun 04 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.15-1
- Update to 1.0.15

* Wed May 27 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.14-1
- Update to 1.0.14

* Wed May 13 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.13-1
- Update to 1.0.13

* Wed May 06 2026 Ryan Brue <ryan.brue@enovationcontrols.com> - 1.0.12-1
- Update to 1.0.12

* Thu Apr 23 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.11-1
- Update to 1.0.11

* Thu Apr 16 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.10-1
- Update to 1.0.10

* Thu Apr 09 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.9-1
- Update to 1.0.9

* Thu Feb 26 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.8-1
- Update to 1.0.8

* Mon Feb 16 2026 Neal Gompa <ngompa@fedoraproject.org> - 1.0.6-4
- Rebuild for libdisplay-info 0.3.0

* Sat Feb 14 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.6-3
- Update cosmic-comp to fix memory leaks

* Sat Feb 14 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.6-2
- Add patch to fix memory leak in cosmic-comp

* Sat Feb 14 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.6-1
- Update to 1.0.6

* Wed Jan 28 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.4-1
- Update to 1.0.4

* Fri Jan 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Fri Jan 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Wed Jan 14 2026 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.2-1
- Update to 1.0.2

* Wed Dec 31 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.1-1
- Update to 1.0.1

* Fri Dec 12 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0-1
- Update to 1.0.0

* Sun Dec 07 2025 Neal Gompa <ngompa@fedoraproject.org> - 1.0.0~beta.9-2
- Add libwayland-server dependency and make libseat dependency arched

* Wed Dec 03 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.9-1
- Update to 1.0.0~beta.9

* Wed Nov 26 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.8-1
- update to 1.0.0~beta.8

* Wed Nov 19 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.7-1
- update to 1.0.0~beta.7

* Thu Nov 13 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.6-1
- update to 1.0.0~beta.6

* Fri Nov 07 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.5-1
- update to 1.0.0~beta.5-1

* Tue Oct 28 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.3-1
- update to 1.0.0~beta.3-1

* Mon Oct 06 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.1.1-1
- update to 1.0.0~beta.1.1-1

* Thu Sep 25 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~beta.1-1
- update to 1.0.0~beta.1-1

* Wed Jul 23 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0~alpha.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Thu Apr 24 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.7-1
- "Update to 1.0.0~alpha.7"

* Tue Mar 11 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.6-2
- Require Xwayland

* Fri Feb 21 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.6-1
- "Update to 1.0.0~alpha.6"

* Thu Jan 16 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0~alpha.5.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Wed Jan 15 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.5.1-1
- "Update to 1.0.0~alpha.5.1"

* Fri Jan 10 2025 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.5-1
- "Update to 1.0.0~alpha.5"

* Fri Dec 06 2024 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.4-1
- "Update to 1.0.0~alpha.4"

* Fri Nov 01 2024 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.3-1
- "Update to 1.0.0~alpha.3"

* Sat Sep 28 2024 Ryan Brue <ryanbrue.dev@gmail.com> - 1.0.0~alpha.2-1
- Update to 1.0.0~alpha.2

* Wed Jul 17 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.0~git20240514.00.36bf611-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Tue May 14 2024 Ryan Brue <ryanbrue@hotmail.com> - 0.1.0~git20240514.00.36bf611-1
- Bump cosmic-comp

* Sat May 04 2024 Ryan Brue <ryanbrue@hotmail.com> - 0.1.0~git20240503.19.19ba568-1
- Update cosmic-comp

* Tue Apr 30 2024 Ryan Brue <ryanbrue@hotmail.com> - 0.1.0~git20240429.18.9022747-1
- Initial import to Fedora (rhbz#2271976)
## END: Generated by rpmautospec
